baseurl = "http://srilankasl.com/"
languageCode = "en-us"
title = "JapanBonsai"
theme = "hugo-cards"
themesDir = "../.."
paginate = 6

[params]
  builtBy = "bool"
  defaultImage = "gopher.jpg"

  facebook = ""
  quora = ""
  twitter = "http://twitter.com/bul_ikana"
  github = "http://github.com/bul-ikana"
  email = ""

  fbLikeBox = ""
  fbAppId = "101630761674046"
  fbPageUrl = ""
  fbPageTitle = ""

  analytics = "UA-156905363-1"
  adsensePublisher = "ca-pub-4554843855357609"
  googleAdsense = "ca-pub-4554843855357609"
  disqus = ""

  custom_css = ["css/custom.css"]

  [params.copyright]
     name = "bool"
     link = "https://bool.netlify.com"
